name: Release

on:
  push:
    branches:
      - master
jobs:
  build:
    if: github.actor != 'carbon-bot' &&	!startsWith(github.event.head_commit.message, 'skip-release')
    name: Create release - Node.js v20.13.1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Use Node.js 20.13.1
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'

      - name: Install dependencies ğŸ”§
        run: yarn install --immutable --check-cache

      - name: Set git user and get git into the right state
        run: |
          git config --global user.email "carbon@us.ibm.com"
          git config --global user.name "carbon-bot"
          git checkout master

      - name: Create version and change logs
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx lerna version --yes --force-publish --conventional-commits --create-release github

      - name: Rebuild packages and demos for publication and deployment ğŸ”§
        run: |
          yarn build
          node scripts/update-angular-dependency-version.mjs

      - name: Publish to npmjs registry and Github
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }} -q
          npx lerna publish from-git --yes --force-publish

      - name: Deploy documentation to Github Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: pages # Folder containing documentation website
          clean: true # Remove deleted files from the deploy branch
