name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.actor != 'carbon-bot' &&	!startsWith(github.event.head_commit.message, 'skip-release')
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set git user to carbon-bot
        run: |
          git config --global user.email "carbon@us.ibm.com"
          git config --global user.name "carbon-bot"

      - name: Use Node.js 20.x LTS
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true
          auth-token: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies ğŸ”§
        run: yarn install --immutable --check-cache

      - name: Generate search index for docs website
        run: lerna run build:search --scope @carbon/charts-docs # should be committed in next step

      - name: Create version and change logs and commit to master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx lerna version --yes --force-publish --conventional-commits --create-release github

      - name: Build latest version's packages (including angular/dist) ğŸ”§
        run: |
          yarn build
          node scripts/update-angular-dependency-version.mjs

      - name: Publish to npmjs registry and Github
        run: npx lerna publish from-git --yes --force-publish

      - name: Deploy documentation to Github Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages # Branch for GitHub Pages
          folder: pages # Folder containing documentation website
          clean: true # Remove deleted files from the deploy branch
